# Generated by Django 5.2.17 on 2026-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_document_document_attachments_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('doc', 'Document'), ('sheet', 'Spreadsheet')], default='doc', max_length=10, verbose_name='kind'),
        ),
    ]
