# Generated by Django 5.2.17 on 2026-09-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_document_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('doc', 'Document'), ('sheet', 'Spreadsheet'), ('folder', 'Folder')], default='doc', max_length=10, verbose_name='kind'),
        ),
    ]
